name: Build Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
      EXPERIMENT_NAME: ${{vars.EXPERIMENT_NAME}}
      MLFLOW_URI: ${{vars.MLFLOW_URI}}
      MODEL_NAME: ${{vars.MODEL_NAME}}
    steps:   
      - name: Generate RUN_NAME
        run: echo "RUN_NAME=run-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
   
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download Adult dataset
        run: |
          mkdir -p data/raw
          curl -o data/raw/adult.data https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
          curl -o data/raw/adult.test https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test

      - name: Train and save model
        run: |
          python src/main.py
        
      - name: Save run ID to env
        run: echo "RUN_ID=$(cat run_id.txt)" >> $GITHUB_ENV
      
      - name: Train and save model
        run: |
          python src/main.py
          
      - name: Run model tests
        run: python model_tests/test_model.py

      - name: Register model in MLflow
        run: python scripts/register_model.py
